{% set name = "des-desmeds" %}
{% set version = "0.9.18" %}

{% set piff = piff or 'cf' %}

{% set build = 2 %}
{% if piff == 'cf' %}
# prioritize piff package
{% set build = build + 100 %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/esheldon/desmeds/archive/v{{ version }}.tar.gz
  sha256: 735db5516a813cc688d36c9f32404b7520540263217fa2d130ceb1a83e562ed5

build:
  # the setup.py uses the `scripts` argument to distutils so this recipe
  # cannot be noarch: python
  number: {{ build }}
  string: "{{ piff }}_h{{ PKG_HASH }}_{{ build }}"
  # weigh down eastlake version with track features
  track_features:                # [piff == "eastlake"]
    - des_desmeds_piff_eastlake  # [piff == "eastlake"]
  skip: true  # [win or py >= 312]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - fitsio
    - des-easyaccess
    - meds
    - esutil
    - pyyaml
    - numpy
    - psfex
    - piff  # [piff == "cf"]
    - galsim
    - pixmappy
    - cfitsio
  # use run constrained to avoid a circular dependency
  run_constrained:        # [piff == "eastlake"]
    - des-eastlake >=0.9  # [piff == "eastlake"]

test:
  imports:
    - desmeds

about:
  home: https://github.com/esheldon/desmeds
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: DES-specific MEDS production code
  doc_url: https://github.com/esheldon/desmeds
  dev_url: https://github.com/esheldon/desmeds

extra:
  recipe-maintainers:
    - beckermr
    - esheldon
