travis:
  secure:
    BINSTAR_TOKEN: j36s2zwTaAaXEAHcLCGAyadBx8+9Pv5nrRit/aPMicJ9G4PJnbm4sDwM+l2/iUl6if/mV4w07ExlKu5dVQnJAa3KnlxRUhs9VXx4yJQV852KnRg/oXjP9g+XYlpzkS6Jab72sjj6fa8ez6KlKz9KmNrvB9H0sHaqnrR+UcV5CfRL9MPHil1Xlxw2MlGkeMUSlRVQ3HPD3l44u1PRt1utAMXMP+Q8CwTeImcZdjMchJslUkfbzejT9Keyyc5pu6DKExcFhoLshYV9neQopyy+mXtGh/1FP6oFQdJFxlCSTOHlS+e6Oz9O6glYRSSWhdmiID3Pyc30QwxuXYdsxX5PNx/MA7yft5OMBPBoNrKmzadQYc0gq8JQaSHmGzRUzBeRSGfd7wNAZJeH5mNrZwoWoA5SO5ilmY/ccrVs3Pm9cSRYfdEzJ6q8vLbNUPfmPap7+AXp11MFzKiY0JoRBHDTlsFjDKJ1TqbgcgN9kqW2pVcE4WfmjUXNuligIatm3f4HVUqZzEZg0qmNnVyflwzFXqxsJ4AJREcURTGJd5qiZIEDP777WR8yOON7JGJ9jvU40sUzHsTq0S3QOmrZnte58z+8+0N5yLAxpoMru1znrupOVwuqpsL7YaIX87TIgO7scyRZg3RkRQap40TztQRU9BbBm1MGzdMLaDmpYt56aKE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
